### ISSUE TITLE
submission form links to 'create github account' and 'fork repo' don't work

### ISSUE THREAD

**Issue by benjaminxscott** [theballaam96/theballaam96.github.io#7]
On the pack builder page:

The buttons to create GH account / fork repo don't open a new tab / have no effect 
(`Chrome Version 124.0.6367.154` , incognito w/ no extensions, JS is allowed)

https://theballaam96.github.io/submission_form

src: https://github.com/theballaam96/theballaam96.github.io/blob/master/submission_form.html

presumably `sendTo()` isn't defined? The page has imports for jquery, bootstrap et.al but I don't see that function defined in those libraries on a quick RTFM

**Comment by theballaam96** [comment]
Good catch, must have made a slight mess-up when shifting the form from GAS to here. Fix has been pushed, should be live in about 5 minutes. Closing issue as complete
